INSERT INTO BANCA (NOME) VALUES('Fundação Carlos Chagas (FCC)');
INSERT INTO BANCA (NOME) VALUES('CESPE');
INSERT INTO BANCA (NOME) VALUES('Cesgranrio');
INSERT INTO BANCA (NOME) VALUES('Fundação Getúlio Vargas (FGV)');
INSERT INTO BANCA (NOME) VALUES('Esaf');

INSERT INTO ORGAO (NOME) VALUES('Tribunal Superior do Trabalho (TST)');
INSERT INTO ORGAO (NOME) VALUES('Senado Federal');
INSERT INTO ORGAO (NOME) VALUES('Tribunal Regional do Trabalho (TRT10)');
INSERT INTO ORGAO (NOME) VALUES('Fundação Hemocentro');
INSERT INTO ORGAO (NOME) VALUES('TJDFT');

INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Direito', NULL);
INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Direito Constitucional', 1);
INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Direito Penal', 1);
INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Direito Tributário', 1);
INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Direito Trabalhista', 1);

INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Português', NULL);
INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Gramática', 6);
INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Literatura', 6);
INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Linguística', 6);
INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Gêneros Textuais', 6);

INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Matemática', NULL);
INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Funções', 11);
INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Equações', 11);
INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Trigonometria', 11);
INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Análise Combinatória', 11);

INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Funções de Primeiro Grau', 12);
INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Funções de Segundo Grau', 12);

INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Redação', 10);
INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Dissertação', 10);
INSERT INTO ASSUNTO(TOPICO, ASSUNTO_PAI) VALUES('Resenha', 10);

INSERT INTO QUESTAO(ENUNCIADO, ASSUNTO_ID, BANCA_ID, ORGAO_ID) values ('A respeito do Romantismo, julgue: Egocentrismo, sentimentalismo e nacionalismo são valores comuns.', 8, 1, 1);
INSERT INTO QUESTAO(ENUNCIADO, ASSUNTO_ID, BANCA_ID, ORGAO_ID) values ('Julgue: Antônio Vieira é um autor que faz parte do barroco brasileiro', 8, 2, 3);
INSERT INTO QUESTAO(ENUNCIADO, ASSUNTO_ID, BANCA_ID, ORGAO_ID) values ('Julgue: O Pré-Modernismo foi um período de intensa movimentação literária que marcou a transição entre o simbolismo e o modernismo.', 8, 3, 4);
